import { Jost, Poppins } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-jost",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Journal Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${jost.variable} font-poppins antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
